"""empty message

Revision ID: 29cb44eb00eb
Revises: f2961f45ed1d
Create Date: 2020-07-11 23:51:44.134002

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29cb44eb00eb'
down_revision = 'f2961f45ed1d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question', sa.Column('answer_timestamp', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('question', 'answer_timestamp')
    # ### end Alembic commands ###
