"""empty message

Revision ID: 4eb4119d27d3
Revises: 8a4b55bb383f
Create Date: 2020-07-09 22:52:25.986075

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4eb4119d27d3'
down_revision = '8a4b55bb383f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('birthdate', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('location', sa.String(length=50), nullable=True))
    op.add_column('user', sa.Column('name', sa.String(length=50), nullable=False))
    op.add_column('user', sa.Column('surname', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'surname')
    op.drop_column('user', 'name')
    op.drop_column('user', 'location')
    op.drop_column('user', 'birthdate')
    # ### end Alembic commands ###
