"""empty message

Revision ID: 817a97134922
Revises: 4eb4119d27d3
Create Date: 2020-07-10 00:01:56.536467

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '817a97134922'
down_revision = '4eb4119d27d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('link', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'link')
    # ### end Alembic commands ###
