"""empty message

Revision ID: 8a4b55bb383f
Revises: f4fbc5c56132
Create Date: 2020-07-09 18:39:03.583920

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a4b55bb383f'
down_revision = 'f4fbc5c56132'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question', sa.Column('answer', sa.String(length=300), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('question', 'answer')
    # ### end Alembic commands ###
