"""empty message

Revision ID: f2961f45ed1d
Revises: 817a97134922
Create Date: 2020-07-10 00:31:22.466249

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2961f45ed1d'
down_revision = '817a97134922'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question', sa.Column('anonymous', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('question', 'anonymous')
    # ### end Alembic commands ###
