"""questions table

Revision ID: f4fbc5c56132
Revises: b3e2a910b8e5
Create Date: 2020-07-07 02:27:06.181079

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4fbc5c56132'
down_revision = 'b3e2a910b8e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question', sa.Column('answered', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('question', 'answered')
    # ### end Alembic commands ###
